### ISSUE TITLE
bcrypt fails at the install script at node-gyp rebuild

### ISSUE THREAD

**Issue by conor909** [ncb000gt/node.bcrypt.js#432]
I get the folowing errors when trying to run `npm install` with `"bcrypt": "^0.8.6"` as a `devDependency`

```
error bcrypt@0.8.7 install: `node-gyp rebuild`
error Exit status 1
error Failed at the bcrypt@0.8.7 install script.
error This is most likely a problem with the bcrypt package,
error not with npm itself.
error Tell the author that this fails on your system:
error     node-gyp rebuild
error You can get their info via:
error     npm owner ls bcrypt
error There is likely additional logging output above.
error System Windows_NT 10.0.10586
error command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
error cwd C:\Users\username\Documents\my-app
error node -v v4.2.4
error npm -v 1.4.3
error code ELIFECYCLE
verbose exit [ 1, true ]
```

Thanks!

**Comment by conor909** [comment]
@defunctzombie why was this closed?

**Comment by conor909** [comment]
For anyone else struggling with this:
http://stackoverflow.com/questions/29320201/error-installing-bcrypt-with-npm

I'm now using `bcrypt-nodejs`, it seems like the exact same api as I didn't have to change code.
`npm install --save bcrypt-nodejs && npm uninstall --save bcrypt`

**Comment by andrewjmead** [comment]
I have the same issue. Shame to to see it getting closed without a conversation. Thanks for the info @conor909.

**Comment by conor909** [comment]
@andrewjmead I just had to edit my previous comment, it's not the same api, you'll need to update your code.

**Comment by bmorelli25** [comment]
Finally working! Thank you @conor909  for the help.

**Comment by scheung38** [comment]
Thanks Conor

I had issue

https://forums.meteor.com/t/another-mup-failed-deployed-any/29277

and now this solved it for me:

    $npm install --save bcrypt-nodejs && npm uninstall --save bcrypt

**Comment by shashidharhr** [comment]
@conor909 
you f**ing life saver man I almost died whole day trying to solve this shit. I love you so much <3.

**Comment by ezyyinc** [comment]
Spent  5 hours trying to get bcrypt to work. SO MUCH THANX HACKER!

**Comment by AravindJakkinapalli** [comment]
I tried doing "npm install --save bcrypt-nodejs && npm uninstall --save bcrypt" and it is fine but when I do npm start, I get an error saying "cannot find module 'bcrypt' ". How do I tell npm not to install bcrypt or even look for it. There is no bcrypt dependency in my package.json. 
![packagejson](https://cloud.githubusercontent.com/assets/22609156/19103991/ccc2aee8-8af7-11e6-9831-75ced78b7a4a.png)
![npmstart](https://cloud.githubusercontent.com/assets/22609156/19104050/f9c379e0-8af7-11e6-9b23-54d72aecc900.png)

**Comment by conor909** [comment]
I think your file in `newproject/mean/module 3/start/app.js` on `line 17` is trying to import or require `bcrypt`.  If that's the case change `"bcrypt"` to `"bcrypt-nodejs"`

**Comment by tanc** [comment]
You need to install with npm version 3: https://github.com/RocketChat/Rocket.Chat/issues/5210
`npm install -g npm@3`

**Comment by fp5885** [comment]
Thanks to tanc. I'm installing kibana4.5 and was getting hung on the bcrypt dependency. npm install -g npm@3 worked for me.

**Comment by adammoisa** [comment]
@conor909 Thumbs up, smiley, party, and heart for you!

**Comment by arorashivani** [comment]
on mac os following solution worked for me
Install Xcode
Run sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

**sources** [https://github.com/nodejs/node-gyp/issues/569](url)

**Comment by azarus** [comment]
Horrible that this is an one year old issue and is still out there causing pain (Y)

**Comment by houssem-yahiaoui** [comment]
Regarding this issue, my solution was to install **bcryptjs** instead of **bcrypt** it's the same package, same api without any messy dependencies, t's fully tested and worked with with **yarn** over **docker**.

Also i guess it will be the suitable solution for everyone out there, if so let's close this old issue !

**Comment by hofman-p** [comment]
Still causes issues in 2018

**Comment by agathver** [comment]
@hofman-p This happens if your machine is incorrectly setup. We have comprehensive installation instructions https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions

Please read them before opening an issue, if it is an obvious case, the issue will be closed without any information, or a link at most depending on the maintainers' mood

**Comment by eduarduo** [comment]
I had the same error and verified that I was using node10, I changed via nvm to node9 and it worked

**Comment by DeepakDonde** [comment]
My solution:
1)Go to visual studio code
2)Open `package.json`
3)Delete bcrypt dependency from `package.json`
4)Now open terminal and run `npm install bcrypt`
5)Restart visual studio code

**Comment by aardvarkk** [comment]
I followed all of the installation instructions at the above link using node 10 and Ubuntu 18.04 and am still having errors building bcrypt.

**Comment by sayhicoelho** [comment]
migrated to https://www.npmjs.com/package/bcryptjs and now everything is working

**Comment by spences10** [comment]
Changing to node 9 fixed the issue for me 👍

**Comment by LukeV111** [comment]
What solved the issue for me was changing my XCode command Line Tools for 10.1 to 9.4 (I have both versions installed).

If you have both versions installed you can do this by going to Xcode > Preferences > Locations and switching you Command Line Tools there. It seems XCOde 10+ is currently incompatible.

**Comment by Nchaka** [comment]
The problem is, installing the bcrypt module re-launches the npm install command after you've explicitly did:

`npm install`

Note: For some packages. You'll notice bcrypt has its own node_modules folder as a module itself.

To remedy the situation of node-gyp or node-pre-gyp being locked out of the equation, you first need to be sure to NOT do sudo as in:

`sudo npm install`

But the trick is, you do need sudo. Therefore you'll have to go with this document https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

Once that is done, you'll be able to simply do `npm install` with the proper privileges, and rebuild successfully.

**Comment by bidipeppercrap** [comment]
SOLUTION: (worked for me)

Install C++ Compiler, make, and Python 2 (Well Linux has it already).
https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions#fedora

**Comment by arulk8** [comment]
i installed bcrypt with compatible version given in there website.it worked for me 
[https://www.npmjs.com/package/bcrypt](https://www.npmjs.com/package/bcrypt)

**Comment by Ishaaqh** [comment]
If u are using nodejs then use `sudo npm install --save bcryptjs`.and restart the server.

**Comment by mlnima** [comment]
please use this package to solve the problem
https://www.npmjs.com/package/bcryptjs

**Comment by mfc3370** [comment]
@conor909 still thanking u in 2019. IS it not possible to collab with the `bcrypt` module programmers? It's crazy everyone using mac has to first `npm i bcrypt`, then fall into the pit and start looking for a solution.

**Comment by akhilasok** [comment]
install `npm i node-pre-gyp` after than `npm i bcrypt`

**Comment by KingZee** [comment]
This is an issue with node-gyp, it doesn't work with Python 3+.

```
sudo apt install python2.7    
ln -s /usr/bin/python2.7 /usr/bin/python
```
Install python 2.7 and set its executable as the default, then install again. If you need python3 later you can always replace the symbolic link.

**Comment by ihemantkumar** [comment]
```
npm ERR! errno 1
npm ERR! bcrypt@3.0.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@3.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I am having this same issue in node v 10.14, 10.15, 10.16. I have tried your above mentioned solutions, but none is working for me.

**Comment by ihemantkumar** [comment]
> This seems to have something to do with npm versions. i had the problem running 11.6.0 but it works fine with 6.1.0, i just used nvm to change versions and npm installed again

If this is the case, how to find which npm version is suitable?

**Comment by iamnoel** [comment]
What an interesting experience. I was getting tons of errors while trying to install for quite a while; at some point I did an npm install node-gyp... and I'm not sure if I added anything else.. still getting various errors until eventually when I was about to give up.. I tried
`npm install --save bcrypt`
That solved it for me. Not sure if it will help anyone else but just adding the **--save** flag allowed me to install bcrypt without all of the errors I was getting before (which were very similar to MANY of the errors I see above)

Good luck everyone!

**Comment by rehan-sattar** [comment]
Still causing this error in 2019.I just migrated to `bcryptjs`, worked 100% fine.
link to the package: https://www.npmjs.com/package/bcryptjs

**Comment by aikhan** [comment]
> on mac os following solution worked for me
> Install Xcode
> Run sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
> 
> **sources** [https://github.com/nodejs/node-gyp/issues/569](url)

It worked it worked :D

**Comment by SachindeepRedsky** [comment]
my solution is:
Use this command
sudo yum groupinstall 'Development Tools'
:)

**Comment by algaly** [comment]
[https://stackoverflow.com/questions/29320201/error-installing-bcrypt-with-npm]
![bcryptjs](https://user-images.githubusercontent.com/485145/71085219-ae89bb00-219f-11ea-9658-abeb0644e0c0.JPG)

**Comment by PolymathWhiz** [comment]
Best solution is to use the node version compatible with the bcrypt version

**Comment by imrizwan** [comment]
Still causing this error in 2020 :/

**Comment by Vanguard90** [comment]
> Best solution is to use the node version compatible with the bcrypt version

For anyone reading this thread, this, in combination of:

> This happens if your machine is incorrectly setup. We have comprehensive installation instructions https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions
>
>Please read them before opening an issue, if it is an obvious case, the issue will be closed without any information, or a link at most depending on the maintainers' mood

solved my problem. I'm currently using Node version `12.15` by the way. Upgraded bcrypt from `1.0.3` to `3.0.8`. Everything works without any problems.

**Comment by RNCTX** [comment]
> @hofman-p This happens if your machine is incorrectly setup. We have comprehensive installation instructions https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions
> 
> Please read them before opening an issue, if it is an obvious case, the issue will be closed without any information, or a link at most depending on the maintainers' mood

False.

2 years later bcrypt@3.0.8 which is listed as compatible with node 12 on NPM will not install globally without passing --unsafe-perm.

**Comment by sanjay-nag** [comment]
I'm still facing this issue!

Bcrypt - 3.0.5
Node - 13.12.0

Tried this (https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions) didn't work!

Stack trace- 


make: Entering directory `/home/ec2-user/kafka-backend/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from /home/ec2-user/.cache/node-gyp/13.12.0/include/node/node.h:67:0,
                 from ../node_modules/nan/nan.h:53,
                 from ../src/bcrypt_node.cc:1:
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8.h:1576:58: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
                                 Local<Value> export_value);
                                                          ^
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8.h:5073:30: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   inline bool IsNeuterable() const {
                              ^
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8.h:5087:22: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   inline void Neuter() { Detach(); }
                      ^
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8.h:5550:76: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
       ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
                                                                            ^
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8.h:6938:28: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   size_t code_range_size() const { return code_range_size_ / kMB; }
                            ^
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8.h:6940:46: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   void set_code_range_size(size_t limit_in_mb) {
                                              ^
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8.h:6944:38: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   size_t max_semi_space_size_in_kb() const;
                                      ^
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8.h:6946:56: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   void set_max_semi_space_size_in_kb(size_t limit_in_kb);
                                                        ^
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8.h:6948:31: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   size_t max_old_space_size() const { return max_old_generation_size_ / kMB; }
                               ^
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8.h:6950:49: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   void set_max_old_space_size(size_t limit_in_mb) {
                                                 ^
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8.h:6954:31: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   size_t max_zone_pool_size() const { return max_zone_pool_size_; }
                               ^
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8.h:6956:43: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   void set_max_zone_pool_size(size_t bytes) { max_zone_pool_size_ = bytes; }
                                           ^
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8.h:7730:75: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   V8_DEPRECATED("Use version with parameter.") virtual void TraceEpilogue() {}
                                                                           ^
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8.h:7785:48: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
       const v8::TracedGlobal<v8::Value>& handle);
                                                ^
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8.h:8455:36: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   Local<Context> GetEnteredContext();
                                    ^
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8.h:8768:75: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   void AddMicrotasksCompletedCallback(MicrotasksCompletedCallback callback);
                                                                           ^
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8.h:8776:78: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   void RemoveMicrotasksCompletedCallback(MicrotasksCompletedCallback callback);
                                                                              ^
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8.h:9207:59: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   static void SetNativesDataBlob(StartupData* startup_blob);
                                                           ^
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8.h:9220:61: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   static void SetFlagsFromString(const char* str, int length);
                                                             ^
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8.h:9305:70: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
                                             const char* snapshot_blob);
                                                                      ^
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8.h:9341:75: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   static bool TryHandleSignal(int signal_number, void* info, void* context);
                                                                           ^
In file included from /home/ec2-user/.cache/node-gyp/13.12.0/include/node/node.h:72:0,
                 from ../node_modules/nan/nan.h:53,
                 from ../src/bcrypt_node.cc:1:
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8-platform.h:371:71: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   virtual void CallOnForegroundThread(Isolate* isolate, Task* task) = 0;
                                                                       ^
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8-platform.h:381:73: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
                                              double delay_in_seconds) = 0;
                                                                         ^
/home/ec2-user/.cache/node-gyp/13.12.0/include/node/v8-platform.h:392:75: warning: ‘deprecated’ attribute directive ignored [-Wattributes]
   virtual void CallIdleOnForegroundThread(Isolate* isolate, IdleTask* task) {
                                                                           ^
In file included from /usr/include/c++/4.8.5/cassert:43:0,
                 from /home/ec2-user/.cache/node-gyp/13.12.0/include/node/node_object_wrap.h:26,
                 from ../node_modules/nan/nan.h:55,
                 from ../src/bcrypt_node.cc:1:
../node_modules/nan/nan_object_wrap.h: In destructor ‘virtual Nan::ObjectWrap::~ObjectWrap()’:
../node_modules/nan/nan_object_wrap.h:24:25: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
     assert(persistent().IsNearDeath());
                         ^
../node_modules/nan/nan_object_wrap.h: In static member function ‘static void Nan::ObjectWrap::WeakCallback(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’:
../node_modules/nan/nan_object_wrap.h:127:26: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
     assert(wrap->handle_.IsNearDeath());
                          ^
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory `/home/ec2-user/kafka-backend/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ec2-user/.nvm/versions/node/v13.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.14.171-105.231.amzn1.x86_64
gyp ERR! command "/home/ec2-user/.nvm/versions/node/v13.12.0/bin/node" "/home/ec2-user/.nvm/versions/node/v13.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/ec2-user/kafka-backend/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/home/ec2-user/kafka-backend/node_modules/bcrypt/lib/binding" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79"
gyp ERR! cwd /home/ec2-user/kafka-backend/node_modules/bcrypt
gyp ERR! node -v v13.12.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/ec2-user/.nvm/versions/node/v13.12.0/bin/node /home/ec2-user/.nvm/versions/node/v13.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ec2-user/kafka-backend/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/ec2-user/kafka-backend/node_modules/bcrypt/lib/binding --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ec2-user/kafka-backend/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 4.14.171-105.231.amzn1.x86_64
node-pre-gyp ERR! command "/home/ec2-user/.nvm/versions/node/v13.12.0/bin/node" "/home/ec2-user/kafka-backend/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/ec2-user/kafka-backend/node_modules/bcrypt
node-pre-gyp ERR! node -v v13.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/home/ec2-user/.nvm/versions/node/v13.12.0/bin/node /home/ec2-user/.nvm/versions/node/v13.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ec2-user/kafka-backend/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/ec2-user/kafka-backend/node_modules/bcrypt/lib/binding --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
npm WARN canvas-backend@1.0.0 No description
npm WARN canvas-backend@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@3.0.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@3.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by agathver** [comment]
@sanjay-nag Use bcrypt >= v3.0.8 with NodeJS 13

**Comment by sanjay-nag** [comment]
> @sanjay-nag Use bcrypt >= v3.0.8 with NodeJS 13
@agathver, thank you for the reply. It worked when I downgraded my node version to 10.x.x

**Comment by salsa-project** [comment]
> For anyone else struggling with this:
> http://stackoverflow.com/questions/29320201/error-installing-bcrypt-with-npm
> 
> I'm now using the `bcrypt-nodejs` library.
> `npm install --save bcrypt-nodejs && npm uninstall --save bcrypt`
> 
> I've been using it without any issues for a while now.

Ty .. working great

**Comment by AzeemAleem** [comment]
@conor909 Thanks Dear
Successfully run the code

**Comment by JavaLavaMT** [comment]
@tanc > pm install -g npm@3

solid fix!

**Comment by yashi32** [comment]
> For anyone else struggling with this:
> http://stackoverflow.com/questions/29320201/error-installing-bcrypt-with-npm
> 
> I'm now using the `bcrypt-nodejs` library.
> `npm install --save bcrypt-nodejs && npm uninstall --save bcrypt`
> 
> I've been using it without any issues for a while now.

@conor909 u saved the day man!!!

**Comment by PaulMabille** [comment]
I had a similar issue in a project using bcrypt. It appears that it came from the bcrypt version in my package.json file. I solved it by reinstalling bcrypt. I would not recommend using bcrypt-nodejs as it is depreciated.

**Comment by yashi32** [comment]
@PaulMabille can you tell the alternative to bcrypt.

**Comment by PaulMabille** [comment]
@yashi32 i didn't use an alternative, i reinstalled it. It was the old version that was causing the issue.

**Comment by netlander** [comment]
This bcrypt module has been a pain for so many years, unbelievable!

**Comment by mohammad3developer** [comment]
> For anyone else struggling with this:
> http://stackoverflow.com/questions/29320201/error-installing-bcrypt-with-npm
> 
> I'm now using the `bcrypt-nodejs` library.
> `npm install --save bcrypt-nodejs && npm uninstall --save bcrypt`
> 
> I've been using it without any issues for a while now.

THHAAAAAAAAAANKS A LOT 
IT'S WOOOOOORK FINALYYYYY

**Comment by xyanlucasx** [comment]
Ubuntu 18.04

it worked for me ->  sudo apt-get install build-essential 

no other solution present here had worked.

It was a new machine (azure VM) and I had forgotten and installed this package.

**Comment by joaogabrieljs** [comment]
> Ubuntu 18.04
> 
> it worked for me -> sudo apt-get install build-essential
> 
> no other solution present here had worked.
> 
> It was a new machine (azure VM) and I had forgotten and installed this package.

This works for me on Ubuntu 18.04 EC2 Instance. Thanks!

**Comment by nodesl** [comment]
> For anyone else struggling with this:
> http://stackoverflow.com/questions/29320201/error-installing-bcrypt-with-npm
> 
> I'm now using the `bcrypt-nodejs` library.
> `npm install --save bcrypt-nodejs && npm uninstall --save bcrypt`
> 
> I've been using it without any issues for a while now.

if anyone still struggle with bcrypt on Amazon Linux, try bcryptjs. coz bcrypt-nodejs has deprecated now

npm install --save bcryptjs && npm uninstall --save bcrypt

replace your const bcrypt = require('bcrypt') with const bcrypt = require('bcryptjs') and everything will work fine : )

**Comment by FahmyChaabane** [comment]
Same goes for me as well in 2021 : 
Ubuntu 20.04, Node v14.15.5
"bcryptjs" fixed everything. wonder why there's two of them. 
Also i tried "bcrypt" in a window machine, same version of noden and it was installed succefully.

**Comment by QiangGuZi** [comment]
still causing this error in 2021

**Comment by haochangindependentsolutions** [comment]
> Thanks Conor
> 
> I had issue
> 
> https://forums.meteor.com/t/another-mup-failed-deployed-any/29277
> 
> and now this solved it for me:
> 
> ```
> $npm install --save bcrypt-nodejs && npm uninstall --save bcrypt
> ```

You don't how long it take for me to find this solutions. only this works for me.
Tried so many  many ways and none of them work.

**Comment by youds** [comment]
Reinstalling worked for me, code modifications weren't advisable. Using AlmaLinux 'dnf install python3-bcrypt' fixed the problems.

**Comment by bttger** [comment]
My problem was that node-gyp always fell back to using python 3 instead of 2. I simply ran a node container to install my dependencies including bcrypt so that I had not to install or/and change other stuff on my PC.

```bash
sudo docker run -v /home/tom/Documents/my-node-server/:/home/ -it --rm --name install-deps node:14 sh
cd home
npm ci
exit
```

**Comment by ArthurBrito** [comment]
For my docker image I had to run that **before** the **npm i**:
```
RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
    && apk del .gyp
```
for my computer (linux mint): `sudo apt-get install build-essential`

**Comment by kanlanc** [comment]
I got this error while installing in docker and for me updating the version of bcrypt to 5.0.0 in package.json worked for me.

**Comment by yrjkqq** [comment]
maybe you set wrong node_gyp config, i just use ```npm config set node_gyp /usr/local/bin/node-gyp```, and then the probleam solved.

**Comment by amos-whitewolf** [comment]
@ArthurBrito Worked for me thank you!

**Comment by solomen5555** [comment]
The solution to this error is :
First ****npm uninstall bcrypt****  or **npm uninstall bcrypt-nodejs** ( if bcrypt or bcrypt-nodejs exist in package.json 
Then **npm install bcryptjs**  
I try to use bcrypt-nodejs but it only helps to push to heroku without error , but it will give error when hashing and genSalt ,
I think   npm install bcryptjs  is the best solution

**Comment by sunsetjesus** [comment]
works with node - **v14.17.0** npm - **v6.14.13**

**Comment by dantaeusb** [comment]
I don't think replacing it with another solution is a proper fix. As I understand, `bcrypt-nodejs`/`bcryptjs` is a much slower alternative.

For me, carefully following readme's helped narrow down the issue, so I tl;dr it here:
1) Check that you have `make`, `build-essential` (or `gcc` I guess), `python` installed (probably other packages for other OSes, like cpp redist for windows);
2) Check that correct version requested according to compatibility table in repo readme. (i.e. 3.0.6+ for node 12+).

After correcting packages and versions, the package was installed without any problems. Hope that helps someone who got here with Google.

By the way, wiki page mentioned here: https://www.npmjs.com/package/bcrypt-nodejs does not exit.

**Comment by atljoseph** [comment]
Thank you Conor!

**Comment by enixlabs** [comment]
#ISSUE: Same as everyone else
#Problem: NPM isn't installing full package requirements and so it misses key libraries for Bcrypt.
Resolved: Our resolution after trying everything and not getting anywhere, was to use

```css
Yarn add bcrypt
```

We also found when we ran yarn, actually a lot of our dependencies are missing key libraries.

Our build is Node v16 & Bcrypt 5.0.1

**Comment by wissalmh** [comment]
I have tried => npm upgrade
then => npm install 
and it worked for me

**Comment by paulomsimoes** [comment]
In node v14.16.0 I only tried:

<**npm install --save bcrypt@5.0.0**>. It worked.

*It used a request for node-pre-gyp https download.

**Comment by alanionita** [comment]
This is still an issue on node v8.15.1 and bcrypt v3.0.8 and node-pre-gyp installed

**Comment by ErtanOzdemir** [comment]
> sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

Thank you sooo much. It worked on Mac - M1 👍

**Comment by ErtanOzdemir** [comment]
> My solution: 1)Go to visual studio code 2)Open `package.json` 3)Delete bcrypt dependency from `package.json` 4)Now open terminal and run `npm install bcrypt` 5)Restart visual studio code(Always a good practice if things not working :))

Thank you sooo much. It worked on Mac - M1 👍 
I firstly changed my node version to current stable version. Then I applied this method

> "node-gyp only works with stable/released versions of node. Since the bcrypt module uses node-gyp to build and install, you'll need a stable version of node to use bcrypt. "

**Comment by bohdan-casafari** [comment]
> My solution: 1)Go to visual studio code 2)Open `package.json` 3)Delete bcrypt dependency from `package.json` 4)Now open terminal and run `npm install bcrypt` 5)Restart visual studio code(Always a good practice if things not working :))

Thanks
works for me

**Comment by Karanpal97** [comment]
hey community i am getting an errorr while installing the bcrypt i issue started when i switched from windows to ubuntu plz someOne help

karan@karan-WD:~/Desktop/ReactBlog/blogAppwrite$ npm i bcrypt
npm ERR! code 7
npm ERR! path /home/karan/Desktop/ReactBlog/blogAppwrite/node_modules/bcrypt
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build

npm ERR! A complete log of this run can be found in: /home/karan/.npm/_logs/2023-10-28T14_01_59_025Z-debug-0.log

**Comment by sarowarhosen03** [comment]
> hey community i am getting an errorr while installing the bcrypt i issue started when i switched from windows to ubuntu plz someOne help
> 
> karan@karan-WD:~/Desktop/ReactBlog/blogAppwrite$ npm i bcrypt npm ERR! code 7 npm ERR! path /home/karan/Desktop/ReactBlog/blogAppwrite/node_modules/bcrypt npm ERR! command failed npm ERR! command sh -c node-pre-gyp install --fallback-to-build
> 
> npm ERR! A complete log of this run can be found in: /home/karan/.npm/_logs/2023-10-28T14_01_59_025Z-debug-0.log

Try bcryptjs
`npm i bcryptjs`

**Comment by dantaeusb** [comment]
@Karanpal97 need full logs, but likely you need Linux build tools like gcc, python and gyp installed, you can try `sudo apt-get install build-essential` and then `npm i bcrypt again`.
If you're building for the browser - it's ok to use `bcryptjs` in build tools and the only option if you need `bcrypt` tools in the browser.
However, installing `bcryptjs` on node is... controversial alternative - I can't find the better words for that. It'll be slower from roughly 20% to hundreds or thousands times, depending on your application.

**Comment by Karanpal97** [comment]
@dantaeusb I am currently facing an issue while trying to install the bcrypt module in my Node.js project on a Linux system. I have followed the suggestions provided in the GitHub issue discussion, including installing build tools with the command

sudo apt-get update
sudo apt-get install build-essential

However, even after installing these tools, I am still encountering installation errors when running npm install bcrypt. Here is the error message I am receiving:

karan@karan-WD:~/Desktop/ReactBlog/blogAppwrite$ npm i bcrypt
npm ERR! code 7
npm ERR! path /home/karan/Desktop/ReactBlog/blogAppwrite/node_modules/bcrypt
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build

npm ERR! A complete log of this run can be found in: /home/karan/.npm/_logs/2023-10-28T14_01_59_025Z-debug-0.log

Additional Information:

    Operating System: Ubuntu
    Node.js Version: v18.18.0
    npm Version:  10.2.1
I have tried several solutions mentioned in various forums and the official documentation, but the problem persists. Could you please provide further guidance or suggest any additional steps I can take to resolve this issue?

**Comment by Karanpal97** [comment]
https://docs.google.com/document/d/1pNM6M1ex9yb-W3NbiH6pKhawTLZ6b41YUghoZo_lG_E/edit?usp=sharing
this is the google doc link for A complete log of this run can be found in: /home/karan/.npm/_logs/2023-10-28T14_01_59_025Z-debug-0.log
if u could help me in fetching the valuable insight for finding the error

**Comment by dantaeusb** [comment]
@Karanpal97 could you please share the contents of `/home/karan/.npm/_logs/2023-10-28T14_01_59_025Z-debug-0.log`? You can use `gedit /home/karan/.npm/_logs/2023-10-28T14_01_59_025Z-debug-0.log` on Ubuntu IIRC to open that file or just `cat /home/karan/.npm/_logs/2023-10-28T14_01_59_025Z-debug-0.log`. There should be a detailed explanation about the error which caused npm install to fail.

**Comment by dantaeusb** [comment]
@Karanpal97 could you please share the contents of `/home/karan/.npm/_logs/2023-10-28T14_01_59_025Z-debug-0.log`? You can use `gedit /home/karan/.npm/_logs/2023-10-28T14_01_59_025Z-debug-0.log` on Ubuntu IIRC to open that file or just `cat /home/karan/.npm/_logs/2023-10-28T14_01_59_025Z-debug-0.log`. There should be a detailed explanation about the error which caused npm install to fail. 

One thing I forgot to mention is that you also would need `python` as mentioned here https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions#ubuntu-and-derivatives---elementary-linux-mint-etc 
If it doesn't work I would suggest cleaning the cache and changing the npm version as often mentioned here: https://stackoverflow.com/questions/77169253/installing-bcrypt-using-npm-failes-with-error-code-7
Unfortunately I don't have an environment to check out the versions you've mentioned but last time I used native packages it was relatively trouble free so it could totally be some kind of cache issue.

**Comment by Karanpal97** [comment]
@dantaeusb https://docs.google.com/document/d/1pNM6M1ex9yb-W3NbiH6pKhawTLZ6b41YUghoZo_lG_E/edit?usp=sharing
the above google contain the complete log kindly see what is the issue

**Comment by Karanpal97** [comment]
@dantaeusb thanks for replying it worked ,i was  trying hard to get the solution thanks,can u plz tell me what was the issue i read the above stackoverflow solution

**Comment by dantaeusb** [comment]
@Karanpal97 I would assume it just tried to get the wrong package since you mentioned you moved from another environment. Node packages that use native libraries require  binaries that are optimized and ready to run on your system specifically. You either download those from npm (if you use popular OS, CPU instruction set, node version developers typically supply ready to use binaries) or build on your own. Two things could go wrong: it was getting a package for the wrong environment (so `npm cache clean` helped) and if your environment has no packages ready - bcrypt build binaries only for stable versions - changing versions might have helped. Or if no binaries were ready, `apt-get install -y build-essential python` installed the required tools to build a binary on your own, and then on the next `npm install` it built the binary for you.

**Comment by FauxFaux** [comment]
It's something to do with the way the snap package for npm's confiment works, if you manually run it outside the sandbox, or with an fnm-provided version of `node` it works fine.

Fine:
```
/snap/node/7823/bin/node /snap/node/7823/bin/npm install bcrypt
```

Not fine:
```
/snap/bin/node  /snap/node/7823/bin/npm install bcrypt
```

I'm unable to e.g. `strace` through snap-confine and don't care about it, so can't guess what that error 7 really means, but I'm going to guess "snap sandbox kill", despite sandboxing being off.

**Comment by Swapnil7711** [comment]
> npm install --save bcrypt-nodejs

Thanks a lot. spent hours trying to fix error but finally this worked like magic.

**Comment by kaplona** [comment]
Is there plan to switch to `python3`? Because it's [very hard to get `python2` on Ubuntu 23](https://ubuntuforums.org/showthread.php?t=2486174), you can't `sudo apt-get install python` any more. I have exact setup and error that @Karanpal97 had, but in my case nothing works without `python2`.

**Comment by kaplona** [comment]
Summary of what helped me for the following setup:
```
Ubuntu 23
Node 18.19.0
npm 10.2.3
bcrypt 5.1.1
```

For bcrypt to work, you need `node-gyp` as stated in the [package docs](https://www.npmjs.com/package/bcrypt#dependencies).

```
npm install -g node-gyp
```

`node-gyp` itself [requires other dependencies](https://github.com/nodejs/node-gyp?tab=readme-ov-file#on-unix): `make`, `gcc`, and `python`. The first two you can get one-by-one or by installing `build-essential`:

```
sudo apt-get install build-essential
```

`node-gyp` works with `python3`, don't let [bcrypt's wiki page](https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions#ubuntu-and-derivatives---elementary-linux-mint-etc) that was referenced in this github issue a lot confuse you.

```
sudo apt-get install python3
```

And then as suggested by @dantaeusb, clean cache and, I would add, remove node modules, that last piece was crucial for my setup to finally start working:

```
rm -rf node_modules
npm cache clean --force
npm install
```

**Comment by yohannesmengistu** [comment]
this npm install --save bcrypt@5.0.0 one works for me

**Comment by natedevwrld** [comment]
> I get the folowing errors when trying to run `npm install` with `"bcrypt": "^0.8.6"` as a `devDependency`
> 
> ```
> error bcrypt@0.8.7 install: `node-gyp rebuild`
> error Exit status 1
> error Failed at the bcrypt@0.8.7 install script.
> error This is most likely a problem with the bcrypt package,
> error not with npm itself.
> error Tell the author that this fails on your system:
> error     node-gyp rebuild
> error You can get their info via:
> error     npm owner ls bcrypt
> error There is likely additional logging output above.
> error System Windows_NT 10.0.10586
> error command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
> error cwd C:\Users\username\Documents\my-app
> error node -v v4.2.4
> error npm -v 1.4.3
> error code ELIFECYCLE
> verbose exit [ 1, true ]
> ```
> 
> Thanks!

use `yarn add bcrypt`

**Comment by vieyama** [comment]
I use python venv and it solve for me:
```bash
python3 -m venv myenv

source myenv/bin/activate  
```
